In [ ]:
import numpy as np

In [ ]:
np

Creating arrays

In [ ]:
np.zeros(10)

In [ ]:
np.ones(10)

In [11]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [15]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [18]:
a[2] = 10

In [19]:
a

array([ 1,  2, 10,  5,  7, 12])

In [22]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi-dimentional arrays

In [24]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a